### ISSUE TITLE
Attractive hover-effect at site navigation

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#1]
On homepage.html, at header-right there is _no hover effect on Lessons/Sign in/Log on_.

Add a good looking hover effect.

**Comment by MuditWadhwa** [comment]
Hi, I would like to contribute to this repository by solving this issue. Please assign this issue to me.

**Comment by rajmunkhan** [comment]
hey, @KanjiyaJinesh I have created one smooth hover effect on your nav links, check them out and merge the pr if you liked it.
