### ISSUE TITLE
Add the special effect to the button 'start_learning'

### ISSUE THREAD

**Issue by jiiinal** [MSTC-DA-IICT/We-demy#17]
- The special effect to the button 'start_learning' should appear on click
- Aspects of the special effect is up to you

**Comment by Sanket2055** [comment]
can i take this issue ?

**Comment by KanjiyaJinesh** [comment]
@Sanket2055  Yes, you can take this issue.
There is no hosted link.
You just need to add effect on the button when it get clicked.
Also add a good hover effect.(Optional)

**Comment by evasharma12** [comment]
I can fix this issue. Please assign it to me.

**Comment by Sanket2055** [comment]
@KanjiyaJinesh done , please check it. #25
