### ISSUE TITLE
Three more lessons to add

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#3]
Add three lessons below four lessons already there on the website.
1. Meteorology
2. Astrology
3. Geology

_Add three lessons with the same style as above. Use any of the background images of above._

**Comment by khushali77** [comment]
Can I take this up?

**Comment by Sonukumarkeshri4** [comment]
Please assign this task to me

**Comment by KanjiyaJinesh** [comment]
@khushali77  assigning to you.

**Comment by KanjiyaJinesh** [comment]
@Sonukumarkeshri4  you can work on this issue
