### ISSUE TITLE
add  missing border bottom after contact us section.... currently bleeding into the footer section.

### ISSUE THREAD

**Issue by batistaDev1113** [MSTC-DA-IICT/We-demy#34]
**Describe the bug**
I would like to add the missing border bottom at the end of the contact us section.  Right the content is bleeding into the footer section, making hard to see where that section end and where the footer begins.

**To Reproduce**

1. Scroll down to 'Contact us'

**Expected behavior**
A border bottom should divide the sections as per the rest of the page

**Screenshots**
![Screen Shot 2021-10-11 at 11 05 23 AM](https://user-images.githubusercontent.com/15971206/136813299-dc121f73-10eb-4946-8c7c-4fcaf16ea1e0.png)

**Desktop (please complete the following information):**
 - Browser [chrome, firefox, etc..]

@KanjiyaJinesh  or @Jinal-Prajapati Please revise and assign to me... thank you!

**Comment by KanjiyaJinesh** [comment]
@batistaDev1113  , Thanks for pointing out.
Do one more thing, apply the CSS to 'Send' button of Contact Us same as 'Start Learning'
