### ISSUE TITLE
Increase width on contact us form to a more appealing and uniform look.  It would look wider and centered.

### ISSUE THREAD

**Issue by batistaDev1113** [MSTC-DA-IICT/We-demy#36]
**Is your feature request related to a problem? Please describe.**
At the moment, the contact us form looks too small and pushed to the left side.  

**Describe the solution you'd like**
I would like to increase size and center the form in the page for a nicer UX design to the user.

Please refer below to how i would like to make it look:

Before:

![Screen Shot 2021-10-11 at 9 52 19 PM](https://user-images.githubusercontent.com/15971206/136877543-6f071f8d-6da4-4679-9904-c923fdf2c2cb.png)

After:

![Screen Shot 2021-10-11 at 9 51 25 PM](https://user-images.githubusercontent.com/15971206/136877486-7ef0a165-6e84-4fc2-b0aa-7bab6006f91f.png)

@KanjiyaJinesh should you feel this is a better UX design, please assign this issue to me
Thank you 👍🏻

**Comment by KanjiyaJinesh** [comment]
@batistaDev1113  LGTM. Make a PR

**Comment by benardcharumbira** [comment]
@KanjiyaJinesh  this has been addressed on the PR for making the site responsive
