### ISSUE TITLE
Make whole website responsive

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#37]
The current website is not responsive to all type of devices.

We-demy should be `responsive` to mobile as well as tablet view.
Don't edit in the same homepage.css file, please make a new CSS file `responsive.css`.

#### some suggestions
- In mobile view all lessons should be in the single column
- In tablet view - two lessons per row(i.e., 2 columns)

**Comment by benardcharumbira** [comment]
@KanjiyaJinesh may you please assign this to me

**Comment by KanjiyaJinesh** [comment]
@benardcharumbira  assigning to you.

**Comment by Harvansh-1234** [comment]
Can I fix this issue?

**Comment by benardcharumbira** [comment]
> Can I fix this issue?

@Harvansh-1234  its already done
