### ISSUE TITLE
hide menu-icon for PC view and add drop-down in mobile view

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#4]
On the homepage menu icon is not hidden in PC view. And add  drop-down in the mobile view.

- Hide the menu-icon in the PC view
- In the mobile view, menu-icon should be visible and Lessons, Sign in, Log in should be in the drop-down.
- Make a _good looking drop-down and add transition._

**Comment by ashutosh2730** [comment]
@KanjiyaJinesh  Assign this to me.

**Comment by KanjiyaJinesh** [comment]
Assigning to you.

**Comment by mayankpal18** [comment]
Hey @KanjiyaJinesh I wanna to solve this issue , will u please assign it to me?

**Comment by Ardent10** [comment]
still open?

**Comment by rockingrohit9639** [comment]
> On the homepage menu icon is not hidden in PC view. And add drop-down in the mobile view.
> 
> * Hide the menu-icon in the PC view
> * In the mobile view, menu-icon should be visible and Lessons, Sign in, Log in should be in the drop-down.
> * Make a _good looking drop-down and add transition._

Can I work on this?

**Comment by KanjiyaJinesh** [comment]
@Ardent10  yes it is still open. : )
@rockingrohit9639  you can work on this.

**Comment by rockingrohit9639** [comment]
> @Ardent10 yes it is still open. : ) @rockingrohit9639 you can work on this.

Hey @KanjiyaJinesh is it necessary to create a dropdown, or I can create a side menu for mobile?
