### ISSUE TITLE
Design the We-demy logo and add it on the website

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#5]
Design the `We-demy logo` and `add on the website`.

1. Make an eye catching logo for We-demy. 
2. Add it on the header.
3. Also add the small-sized logo at the bottom just above 'Enjoy Learning, So You Can Enjoy Future.'

**Comment by singhshobhit12a** [comment]
please assign it to me.

**Comment by KanjiyaJinesh** [comment]
@singhshobhit12a  assigning to you. Please add screenshot/short video while commit.

**Comment by singhshobhit12a** [comment]
I HAVE COMMITTED THE FILES ALONG WITH A 2SEC VIDEO AND LOGO
