### ISSUE TITLE
Background image on the top

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#7]
Red background of the top-wrapper is to be change with an image.

- Image should be themed on study/books/online teaching.
- Must be dark, so that content on the top in white color should be clearly visible.
- Should cover the whole width(wherever the red color you see).

**Comment by khushali77** [comment]
Can I work on this issue?

**Comment by KanjiyaJinesh** [comment]
Sure you can work on this.

**Comment by shantanu-crypto** [comment]
Can I also contribute on this issue?

**Comment by yrs-rosh** [comment]
Can I work on this issue?

**Comment by KanjiyaJinesh** [comment]
Sorry @yrs-rosh , I closing this issue. You can work on the other issue.
