### ISSUE TITLE
Add log in page

### ISSUE THREAD

**Issue by KanjiyaJinesh** [MSTC-DA-IICT/We-demy#8]
Add a **`separate login page`** from the homepage login button.

- Should contain email ID or facebook id or twitter id as Account info and password.
- A good interface is must.

**Comment by shantanu-crypto** [comment]
Can i work on this?

**Comment by KanjiyaJinesh** [comment]
@shantanu-crypto  yes you can work on this issue.

**Comment by shantanu-crypto** [comment]
Sorry sir i am getting some error that i am unable to solve.

**Comment by KanjiyaJinesh** [comment]
@shantanu-crypto  No problem

**Comment by ParmarKrishna** [comment]
Can I work on this issue?

**Comment by KanjiyaJinesh** [comment]
@ParmarKrishna  you can work on this issue

**Comment by mrdevil0-9** [comment]
can i work  on  this project issue

**Comment by KanjiyaJinesh** [comment]
@ParmarKrishna  can you tell me, what is the status of the work you are doing.

**Comment by ParmarKrishna** [comment]
@KanjiyaJinesh It's almost done. You can expect PR in some time.
